[package]
name    = "blightos"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
name = "kernel"
path = "src/kernel.rs"


[features]
debug_kern = []
debug_arch = []
debug_systimer = []
debug_mmu  = []
debug_pmm  = []
debug_heap = []
debug_virt = []
debug_sched= []
debug_pci  = []
debug_ahci = []
debug_emmc = []
debug_ihda = []
debug_gui  = []
